package org.ext4spring.parameter.converter.tv;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;

import org.ext4spring.parameter.converter.Converter;

/**
 * Simple converter uses .toString and .valueOf for conversion
 * Can convert any class that match the following criteria:
 * -Has a String constructor or has a valueOf(String) method that creates an instance from a String
 * -The string generated by .toString can passed to the constructor or the valueOf method to create the object.
 * @author pborbas
 *
 */
public class TVConverter implements Converter {

    @Override
    public Class<?> getHandledClass() {
        return Object.class;
    }

    @Override
    public <T> T toTypedValue(String stringValue, Class<T> type) {
        try {
            try {
                //with string constructor
                Constructor<T> constructor=type.getConstructor(String.class);
                T typedValue=constructor.newInstance(stringValue);
                return typedValue;
            } catch (NoSuchMethodException e) {
                //with noarg constructor and valueof
                T typedValue=type.newInstance();
                Method method=type.getMethod("valueOf", String.class);
                method.invoke(typedValue, stringValue);
                return typedValue;
           }
        } catch (InstantiationException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        } catch (SecurityException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        } catch (NoSuchMethodException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        } catch (IllegalArgumentException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        } catch (InvocationTargetException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        return null;
    }

    @Override
    public String toStringValue(Object typedValue) {
        return typedValue.toString();
    }

    public static void main(String[] args) {
        TVConverter tvConverter=new TVConverter();
        tvConverter.toStringValue(tvConverter.toStringValue(new String("string")));
    }
}
