

CREATE TABLE EFS_ACL (
	ACL_ID IDENTITY,
	OBJECT_TYPE VARCHAR(200),
	OBJECT_ID VARCHAR(100),
	USER_ID VARCHAR(100),
	ACL_PERMISSION VARCHAR(50)
);

CREATE UNIQUE INDEX efs_acl_idx ON efs_acl(OBJECT_TYPE,OBJECT_ID,USER_ID,ACL_PERMISSION);